<a href="https://colab.research.google.com/github/gorzanskik-ai/python-libraries/blob/main/numpy/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Tablice

In [ ]:
arr = np.array([1, 2])  #wszystkie elementy w tablicy muszą być tego samego typu
print(arr)
print(type(arr))

[1 2]
<class 'numpy.ndarray'>


In [ ]:
print('wymiar tablicy:', arr.ndim)
print('kształt tablicy:', arr.shape)
print('rozmiar tablicy:', arr.size)
print('typ danych w tablicy:', arr.dtype)

wymiar tablicy: 1
kształt tablicy: (2,)
rozmiar tablicy: 2
typ danych w tablicy: int64


In [ ]:
arr2d = np.array([[1, 2], [3, 4]])  #tablica 2D

In [ ]:
print('wymiar tablicy:', arr2d.ndim)
print('kształt tablicy:', arr2d.shape)
print('rozmiar tablicy:', arr2d.size)
print('typ danych w tablicy:', arr2d.dtype)

wymiar tablicy: 2
kształt tablicy: (2, 2)
rozmiar tablicy: 4
typ danych w tablicy: int64


In [ ]:
arr3d = np.array([[[1, 2, 3],  #tablica 3D
                    [1, 2, 3]],
                   [[1, 2, 3],
                    [1, 2, 3]]])

In [ ]:
print('wymiar tablicy:', arr3d.ndim)
print('kształt tablicy:', arr3d.shape)  #(tablice, wiersze, kolumny)
print('rozmiar tablicy:', arr3d.size)
print('typ danych w tablicy:', arr3d.dtype)

wymiar tablicy: 3
kształt tablicy: (2, 2, 3)
rozmiar tablicy: 12
typ danych w tablicy: int64


Inne sposoby tworzenia tablic

In [ ]:
arr = np.zeros(shape=(3, 3), dtype='int')   #tablica zer
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.ones(shape=(3, 3), dtype='int')   #tablica jedynek
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr = np.full(shape=(3, 3), fill_value=11, dtype='int') #tablica złożona z podanych przez nas wartośsci
print(arr)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(start=0, stop=101, step=3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
arr = np.linspace(start=1, stop=101, num=27)    #zwraca 'num' elementów równo rozłozonych z przedialu (start, stop)
print(arr)

[  1.           4.84615385   8.69230769  12.53846154  16.38461538
  20.23076923  24.07692308  27.92307692  31.76923077  35.61538462
  39.46153846  43.30769231  47.15384615  51.          54.84615385
  58.69230769  62.53846154  66.38461538  70.23076923  74.07692308
  77.92307692  81.76923077  85.61538462  89.46153846  93.30769231
  97.15384615 101.        ]


Zmiana kształtu tablicy

In [ ]:
A = np.arange(15)
print(A)
A = A.reshape((3, 5))
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
A.reshape(5, -1)    #-1 oznacza optymalne dobranie ilości kolumn do podanych wierszy i odwrotnie

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Operacje na tablicach

In [ ]:
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

In [ ]:
print(A + B)    #Dodawanie
print(np.add(A, B))

[2 4 6]
[2 4 6]


In [ ]:
print(A - B)    #Odejmowanie
print(np.subtract(A, B))

[0 0 0]
[0 0 0]


In [ ]:
print(A * B)    #Mnożenie, ale nie macierzowe tylko po kolejnych liczbach (element po elemencie)
print(np.multiply(A, B))

[1 4 9]
[1 4 9]


In [ ]:
print(A / B)    #Dzielenie
print(np.divide(A, B))

[1. 1. 1.]
[1. 1. 1.]


In [ ]:
X = np.array([[1, 2],
              [1, 2]])
Y = np.array([[7, 8],
              [7, 8]])

In [ ]:
np.matmul(X, Y)     #Prawdziwe monżenie macierzy

array([[21, 24],
       [21, 24]])

In [ ]:
np.dot(X, Y)

array([[21, 24],
       [21, 24]])

In [ ]:
X.dot(Y)

array([[21, 24],
       [21, 24]])

In [ ]:
X @ Y

array([[21, 24],
       [21, 24]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.randn(10, 4)  #liczby z rozkładu normalnego

array([[-0.730768  , -0.84542388,  0.11009119,  1.03413543],
       [ 1.15605886, -0.07498426, -1.36093906, -0.76252839],
       [-1.21719622, -0.63184376, -1.44529212, -1.3431103 ],
       [-0.14975043,  0.84419394, -0.17493886,  0.19123608],
       [-1.44704958,  0.09588992,  1.66584834,  1.36877319],
       [-0.13955885, -1.0448072 ,  0.40201865,  1.20422437],
       [ 0.23513356, -0.63683484, -1.17161571,  0.22281469],
       [ 0.80239116,  0.14666541, -0.93234097,  0.25106191],
       [ 0.23223061, -0.24385796,  1.23217798, -0.26674401],
       [-0.30844574, -0.8908769 ,  1.60732291, -0.56583331]])

In [ ]:
np.random.rand(10, 4) #liczby z przedziału {0, 1)

array([[0.07055287, 0.48150763, 0.32429937, 0.29065037],
       [0.50903601, 0.03160459, 0.14555808, 0.17030374],
       [0.1491574 , 0.20471477, 0.37328326, 0.10676798],
       [0.67695182, 0.73811279, 0.34341722, 0.56446485],
       [0.04150677, 0.58941264, 0.6484678 , 0.32711194],
       [0.3872179 , 0.11388882, 0.75624294, 0.65363108],
       [0.26224337, 0.11814305, 0.64808268, 0.16332013],
       [0.67168761, 0.83997691, 0.29343804, 0.99857043],
       [0.08874418, 0.38114785, 0.32642002, 0.22565478],
       [0.94243839, 0.20562325, 0.27760896, 0.47236903]])

In [ ]:
np.random.randint(low=10, high=100, size=100)   #100 liczb int z przedziału od 10 do 99

array([64, 55, 96, 22, 96, 18, 19, 83, 34, 21, 73, 37, 79, 49, 68, 40, 64,
       35, 49, 71, 49, 16, 82, 78, 32, 67, 69, 48, 82, 47, 53, 67, 82, 17,
       68, 83, 69, 83, 86, 91, 23, 31, 34, 28, 32, 86, 23, 49, 50, 30, 74,
       75, 76, 25, 87, 21, 30, 97, 52, 36, 45, 19, 74, 68, 94, 15, 17, 59,
       29, 56, 71, 79, 70, 74, 61, 11, 25, 65, 66, 64, 18, 51, 46, 48, 11,
       51, 15, 25, 97, 99, 99, 70, 95, 33, 39, 22, 73, 22, 68, 25])

In [ ]:
np.random.choice([1, 2, 3, 4, 5])   #losowy wybór z iterowalnego obiektu

3

In [ ]:
np.random.choice(['java', 'python', 'sql'])

'python'

In [ ]:
a = np.arange(10)   #losowe przetasowanie elementów
np.random.shuffle(a)
a

array([4, 1, 9, 0, 6, 3, 8, 7, 2, 5])

In [ ]:
x = [i for i in range(20)]
np.random.shuffle(x)
print(x)

[5, 17, 2, 1, 16, 14, 11, 15, 12, 7, 6, 0, 4, 3, 10, 9, 18, 8, 19, 13]


Poddstawowe funkcje w numpy

In [ ]:
np.exp(1) #e^x

2.718281828459045

In [ ]:
np.sqrt(9) #pierwiastek

3.0

In [ ]:
np.all([1, 2, 3, True]) #jeśli wszystkie elementy są True to True, jeśli nie to False

True

In [ ]:
np.any([True, False, False]) #jeśli co najmniej jeden element jest True to True jeśli nie to Fasle

True

In [ ]:
np.random.seed(10)
A = np.random.rand(5)
A

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [ ]:
print('indeks najwiekszej wartości:', np.argmax(A))
print('indeks najmniejszej wartości:', np.argmin(A))
print('indeksy posortowanych wartości:', np.argsort(A))
print('wartość największa:', np.max(A))
print('wartość najmniejsza:', np.min(A))
print('średnia:', np.mean(A))
print('mediana:', np.median(A))
print('odchylenie standardowe:', np.std(A))

indeks najwiekszej wartości: 0
indeks najmniejszej wartości: 1
indeksy posortowanych wartości: [1 4 2 3 0]
wartość największa: 0.771320643266746
wartość najmniejsza: 0.0207519493594015
średnia: 0.534606344478725
mediana: 0.6336482349262754
odchylenie standardowe: 0.2746172033183844


Indeksowanie i wycinanie tablic

In [ ]:
A = np.arange(20)
A[:5]

array([0, 1, 2, 3, 4])

In [ ]:
A[3:]   #indeksowanie tak jak w w pythonie

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
A[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
A[::-2]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [ ]:
A = A.reshape(4, 5)

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0, :3]

array([0, 1, 2])

In [ ]:
A[:, 0]

array([ 0,  5, 10, 15])

In [ ]:
A[2, :]

array([10, 11, 12, 13, 14])

In [ ]:
A[1, 1:4]

array([6, 7, 8])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

Iteracje po tablicach, zmiana rozmiaru, maski logiczne

In [105]:
A = np.arange(20)
A = A.reshape(4, -1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [106]:
for row in A:   #standardowo iterowanie po wierszach
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [107]:
for row in A:
    print(row[::-1])

[4 3 2 1 0]
[9 8 7 6 5]
[14 13 12 11 10]
[19 18 17 16 15]


In [112]:
for item in A.flat: #wypłaszczenie macierzy
    print(item, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [113]:
A.ravel()   #wypłaszczenie macierzy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
A.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [117]:
A.T #transpozycja

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [120]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [121]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [122]:
A[A > 0]    #maski logiczne

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [130]:
A[np.bitwise_and(A > -5, A < 5)]    #łączenie warunków and

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [132]:
A[np.bitwise_and(A > -9, A < -2.5)]

array([-8.5, -8. , -7.5, -7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5,
       -3. ])

In [134]:
A[np.bitwise_or(A < -5, A > 5)] #łączenie warunków or

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])