<a href="https://colab.research.google.com/github/gorzanskik-ai/python-libraries/blob/main/numpy/02_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Norma euklidesowa w R2

In [2]:
v1 = np.array([0, 4])
np.linalg.norm(v1)

4.0

Norma euklidesowa w R3

In [3]:
v2 = np.array([1, 2, 3])
np.linalg.norm(v2)

3.7416573867739413

Odległość dwóch punktów na płaszczyźnie R2

In [4]:
p = np.array([10, 12])
q = np.array([1, 4])
np.linalg.norm(p - q)

12.041594578792296

Odległość dwóch punktów na płaszczyźnie R3

In [5]:
p = np.array([1, 10, 12])
q = np.array([12, 1, 10])
np.linalg.norm(p - q)

14.352700094407323

Mnożenie macierzy

In [11]:
mat1 = np.array([[1, 2],
                [1, 2]])
mat2 = np.array([[12, 12],
                [13, 17]])
print(np.dot(mat1, mat2))
print(np.matmul(mat1, mat2))
print(mat1 @ mat2)

[[38 46]
 [38 46]]
[[38 46]
 [38 46]]
[[38 46]
 [38 46]]


Wyznacznik macierzy  

In [12]:
A = np.array([[2, 4],
              [-1, 3]])
np.linalg.det(A)

9.999999999999998

Ślad macierzy

In [14]:
A = np.array([[2, 4, 12],
              [-1, 3, 12],
              [1, 10, 111]])
np.trace(A)

116

Macierz jednostkowa

In [15]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [22]:
np.set_printoptions(precision=4, suppress=True)
A = np.array([[1, 2],
              [3, 4]])
B = np.linalg.inv(A)
print(B)
print(A @ B)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


Macierz transponowana

In [24]:
A = np.array([[1, 2],
              [3, 4]])
print(A.T)
print(np.transpose(A))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


Rozwiązywanie układu równań

In [26]:
# AX = B
# A^(-1)AX = A^(-1)B
# X = A^(-1)B
A = np.array([[2, 4],
              [1, -1]])
B = np.array([[10],
              [-1]])

X = np.linalg.inv(A) @ B
X

array([[1.],
       [2.]])